In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
# Прочитайте файл и сохраните его в любой переменной
from google.colab import drive
drive.mount('/content/drive/')
%cd /content/drive/MyDrive
df = pd.read_csv('/content/drive/MyDrive/Airpollution.csv')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
/content/drive/MyDrive


In [14]:
# Удалите столбец City из датасета
del df['City']

In [19]:
# Столбец AQI Value выделить как ключевой и удалите для выборки Х, разбейте train и test на выборки
y = df[['AQI Value']]
X= df.drop('AQI Value', axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=42)

In [21]:
 #Проведите Скеллинг данных для X_train и X_test выборки. Необходимо выполнить в два шага с созданием отдельных переменных. Для X_test применить только transform. Выведите отскелиренные таблицы
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.select_dtypes(exclude=['object']))
X_test_scaled = scaler.transform(X_test.select_dtypes(exclude=['object']))
print('X_train')
print(X_train_scaled)
print('X_test')
print(X_test_scaled)

X_train
[[ 0.83311915 -0.7212399   0.5703916   1.48588988]
 [ 0.31830377 -0.7212399   2.50288569 -0.05161032]
 [ 2.89238067 -0.96975207  3.08263392  2.05330067]
 ...
 [ 0.31830377 -0.79224338 -0.58910485 -0.30786035]
 [-0.711327   -0.2597173  -0.20260603 -0.89357471]
 [-0.19651162 -0.79224338 -0.58910485 -0.91187828]]
X_test
[[-0.19651162 -0.36622251  0.3771422  -0.19803891]
 [-0.19651162 -0.61473468 -0.58910485 -0.85696756]
 [-0.19651162  0.09530009 -0.20260603 -0.39937822]
 ...
 [-0.19651162 -0.86324685 -0.20260603 -0.6190211 ]
 [ 0.31830377 -0.36622251  0.76364101 -0.19803891]
 [ 0.31830377 -0.86324685  0.5703916  -0.06991389]]


In [17]:
# Провести OHE для X_train и X_test выборки. Fit и transform для Train проводим в два последовательных отдельных шага.
# Выведите таблицы после OHE на экран.
encoder = OneHotEncoder(handle_unknown='ignore')
X_train_ohe = encoder.fit_transform(X_train.select_dtypes(include=['object']))
X_test_ohe = encoder.transform(X_test.select_dtypes(include=['object']))
print('X_train_ohe')
print(X_train_ohe)
print('X_test_ohe')
print(X_test_ohe)


X_train_ohe
  (0, 162)	1.0
  (0, 175)	1.0
  (0, 178)	1.0
  (0, 181)	1.0
  (0, 186)	1.0
  (0, 191)	1.0
  (1, 162)	1.0
  (1, 174)	1.0
  (1, 178)	1.0
  (1, 181)	1.0
  (1, 186)	1.0
  (1, 190)	1.0
  (2, 140)	1.0
  (2, 175)	1.0
  (2, 178)	1.0
  (2, 181)	1.0
  (2, 186)	1.0
  (2, 191)	1.0
  (3, 43)	1.0
  (3, 175)	1.0
  (3, 178)	1.0
  (3, 181)	1.0
  (3, 186)	1.0
  (3, 191)	1.0
  (4, 142)	1.0
  :	:
  (17592, 190)	1.0
  (17593, 31)	1.0
  (17593, 176)	1.0
  (17593, 178)	1.0
  (17593, 181)	1.0
  (17593, 186)	1.0
  (17593, 192)	1.0
  (17594, 170)	1.0
  (17594, 174)	1.0
  (17594, 178)	1.0
  (17594, 181)	1.0
  (17594, 186)	1.0
  (17594, 190)	1.0
  (17595, 122)	1.0
  (17595, 172)	1.0
  (17595, 178)	1.0
  (17595, 181)	1.0
  (17595, 186)	1.0
  (17595, 188)	1.0
  (17596, 20)	1.0
  (17596, 172)	1.0
  (17596, 178)	1.0
  (17596, 181)	1.0
  (17596, 186)	1.0
  (17596, 188)	1.0
X_test_ohe
  (0, 13)	1.0
  (0, 174)	1.0
  (0, 178)	1.0
  (0, 181)	1.0
  (0, 186)	1.0
  (0, 190)	1.0
  (1, 127)	1.0
  (1, 172)	1.0
  (1,

In [18]:
# Провести объединение датафрейма с помощью pd.concat. X_train OHE с X_train Scaled и также для теста. По итогу вывести на экран два датафрейма.
X_train_scaled_df = pd.DataFrame(X_train_scaled)
X_test_scaled_df = pd.DataFrame(X_test_scaled)

X_train_ohe_df = pd.DataFrame(X_train_ohe)
X_test_ohe_df = pd.DataFrame(X_test_ohe)

concat_train_df = pd.concat([X_train_scaled_df, X_train_ohe_df], axis=1)
concat_test_df = pd.concat([X_test_scaled_df, X_test_ohe_df], axis=1)

print('concat_train_df')
print(concat_train_df)
print('\nconcat_test_df')
print(concat_test_df)

concat_train_df
              0         1         2         3  \
0      0.833119 -0.721240  0.570392  1.485890   
1      0.318304 -0.721240  2.502886 -0.051610   
2      2.892381 -0.969752  3.082634  2.053301   
3      0.833119 -0.863247  1.536639  1.577408   
4     -0.196512 -0.543731 -0.009357 -0.564110   
...         ...       ...       ...       ...   
17592 -0.711327 -0.472728 -0.589105 -0.106521   
17593  0.833119  0.166304 -0.202606  0.845265   
17594  0.318304 -0.792243 -0.589105 -0.307860   
17595 -0.711327 -0.259717 -0.202606 -0.893575   
17596 -0.196512 -0.792243 -0.589105 -0.911878   

                                                       0  
0        (0, 162)\t1.0\n  (0, 175)\t1.0\n  (0, 178)\t...  
1        (0, 162)\t1.0\n  (0, 174)\t1.0\n  (0, 178)\t...  
2        (0, 140)\t1.0\n  (0, 175)\t1.0\n  (0, 178)\t...  
3        (0, 43)\t1.0\n  (0, 175)\t1.0\n  (0, 178)\t1...  
4        (0, 142)\t1.0\n  (0, 172)\t1.0\n  (0, 178)\t...  
...                                      

Сравните данные до масштабирования и после.
Что изменилось?

В результате масштабирования данные приняли более сбалансированный вид, что повысит результативность обучения модели.